// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: query.sql

package book_datasource

import (
	"context"
)

const createBook = `-- name: CreateBook :one
INSERT INTO books (
  name, author
) VALUES (
  $1, $2
)
RETURNING id, name, author
`

type CreateBookParams struct {
	Name   string
	Author string
}

func (q *Queries) CreateBook(ctx context.Context, arg CreateBookParams) (Book, error) {
	row := q.db.QueryRowContext(ctx, createBook, arg.Name, arg.Author)
	var i Book
	err := row.Scan(&i.ID, &i.Name, &i.Author)
	return i, err
}

const deleteBook = `-- name: DeleteBook :exec
DELETE FROM books
WHERE id = $1
`

func (q *Queries) DeleteBook(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteBook, id)
	return err
}

const getBook = `-- name: GetBook :one
SELECT id, name, author FROM books
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetBook(ctx context.Context, id int64) (Book, error) {
	row := q.db.QueryRowContext(ctx, getBook, id)
	var i Book
	err := row.Scan(&i.ID, &i.Name, &i.Author)
	return i, err
}

const listBook = `-- name: ListBook :many
SELECT id, name, author FROM books
ORDER BY name
`

func (q *Queries) ListBook(ctx context.Context) ([]Book, error) {
	rows, err := q.db.QueryContext(ctx, listBook)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(&i.ID, &i.Name, &i.Author); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBook = `-- name: UpdateBook :one
UPDATE books
  set name = $2,
  author = $3
WHERE id = $1
RETURNING id, name, author
`

type UpdateBookParams struct {
	ID     int64
	Name   string
	Author string
}

func (q *Queries) UpdateBook(ctx context.Context, arg UpdateBookParams) (Book, error) {
	row := q.db.QueryRowContext(ctx, updateBook, arg.ID, arg.Name, arg.Author)
	var i Book
	err := row.Scan(&i.ID, &i.Name, &i.Author)
	return i, err
}
